<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<Nullable>enable</Nullable>

		<Title>Stories Data</Title>
		<Description>The schema declarations and durable vocabulary for BigRedProf.Stories.</Description>
		<PackageTags>bigredprof;stories;models</PackageTags>
		<Product>Stories Data</Product>

	</PropertyGroup>

	<Target Name="RunPackRatCompiler" BeforeTargets="Build">
		<Exec WorkingDirectory="$(ProjectDir)" Command="dotnet prc $(ProjectFileName) -o $(IntermediateOutputPath)" ContinueOnError="false" ConsoleToMSBuild="true">
			<Output TaskParameter="ConsoleOutput" PropertyName="OutputOfExec" />
		</Exec>
	</Target>

	<ItemGroup>
		<Compile Include="$(IntermediateOutputPath)\*.g.cs"></Compile>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="BigRedProf.Data.Core" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="obj\" />
	</ItemGroup>

</Project>
