name: .NET

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
      - name: Add NuGet Source
        run: dotnet nuget add source --username BigRedProf --password ${{ secrets.BIGREDPROF_GITHUB_PAT_PACKAGE_REGISTRY }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/BigRedProf/index.json"
        working-directory: src
      - name: Restore
        run: dotnet restore
        working-directory: src
      - name: Restore dotnet tools
        run: dotnet tool restore
        working-directory: src
      - name: Build Debug
        run: dotnet build --no-restore
        working-directory: src
      - name: Test Debug
        run: dotnet test --no-build --verbosity normal
        working-directory: src
      - name: Build Release
        run: dotnet build --no-restore -c Release
        working-directory: src
      - name: Test Release
        run: dotnet test --no-build --verbosity normal -c Release
        working-directory: src
      - name: Pack
        run: dotnet pack -c Release
        working-directory: src
      - name: Push BigRedProf.Stories.Core package
        run: dotnet nuget push ./Core/bin/Release/*.nupkg --source "github" --skip-duplicate
        working-directory: src
      - name: Push BigRedProf.Stories.Logging package
        run: dotnet nuget push ./Logging/bin/Release/*.nupkg --source "github" --skip-duplicate
        working-directory: src
      - name: Push BigRedProf.Stories.Logging.Models package
        run: dotnet nuget push ./Logging.Models/bin/Release/*.nupkg --source "github" --skip-duplicate
        working-directory: src
      - name: Push BigRedProf.Stories.Core.Models package
        run: dotnet nuget push ./Core.Models/bin/Release/*.nupkg --source "github" --skip-duplicate
        working-directory: src
